"""Verifies the schema, cleans the raw CSV, and freezes the train/val/test splits.

    python scripts/prepare_data.py
"""

from __future__ import annotations

import sys

import _bootstrap  # noqa: F401

from sentrynet.config import load_config
from sentrynet.data import (
    ROW_ID,
    count_exact_duplicates,
    file_fingerprint,
    load_raw,
    privacy_review,
    remove_exact_duplicates,
    verify_dataset,
    write_json,
)
from sentrynet.splits import PROTOCOLS, build_splits, split_metadata, write_splits


def privacy_markdown(review: dict) -> str:
    return "\n".join(
        [
            "# Privacy Review",
            "",
            "Generated by `scripts/prepare_data.py`.",
            "",
            "## Conclusion",
            "",
            f"> {review['conclusion']}",
            "",
            "## Evidence",
            "",
            f"- Columns reviewed: `{review['columns_reviewed']}`",
            f"- IP / user / host / MAC / session identifier columns found: "
            f"`{review['identifier_columns_found'] or 'none'}`",
            f"- Free-text or payload columns found: `{review['free_text_columns_found'] or 'none'}`",
            f"- Timestamp columns found: `{review['timestamp_columns_found'] or 'none'}`",
            "",
            "## What was and was not done",
            "",
            f"- Masking performed: **{review['masking_performed']}**",
            f"- Hashing performed: **{review['hashing_performed']}**",
            "",
            "This project does **not** implement IP hashing, user hashing, or MAC stripping,",
            "and does not claim to. There is nothing of that kind in the schema to protect.",
            "Claiming otherwise would be a false security control.",
            "",
            f"{review['note']}",
            "",
            "## Near-duplicate handling",
            "",
            "Only **exact** duplicate rows are removed. Near-duplicate detection would require",
            "a timestamp, IP, user, or session identifier to define proximity, and this",
            "dataset has none of those fields.",
            "",
        ]
    )


def main() -> int:
    cfg = load_config()
    cfg.ensure_dirs()
    csv_path = cfg.path("raw_csv")
    if not csv_path.exists():
        print(
            f"[FAIL] Raw CSV not found at {csv_path}.\n"
            "       Download it from Kaggle and place it there - see the README's "
            "'Reproduce Training' section.",
            file=sys.stderr,
        )
        return 1

    fingerprint = file_fingerprint(csv_path)
    raw = load_raw(csv_path)

    result = verify_dataset(raw, cfg["dataset"])
    if not result.ok:
        failed = [c for c in result.checks if not c["passed"] and c["material"]]
        print(
            "[STOP] Dataset verification failed - the CSV does not match the expected "
            f"schema: {failed}",
            file=sys.stderr,
        )
        return 1

    duplicates_before = count_exact_duplicates(raw, ignore=(ROW_ID,))
    clean, removed = remove_exact_duplicates(raw, ignore=(ROW_ID,))
    print(f"Exact duplicates found: {duplicates_before}; removed: {removed}")
    print(f"Rows before: {len(raw):,}  after: {len(clean):,}")

    clean_path = cfg.path("clean_csv")
    clean.to_csv(clean_path, index=False)
    print(f"Wrote {clean_path}")

    review = privacy_review(clean)
    privacy_path = cfg.path("outputs_dir") / "privacy_review.md"
    privacy_path.parent.mkdir(parents=True, exist_ok=True)
    privacy_path.write_text(privacy_markdown(review), encoding="utf-8")
    print(f"Wrote {privacy_path}")

    cleaning_record = {
        "source_file": str(csv_path),
        "dataset_fingerprint_sha256": fingerprint,
        "rows_before": int(len(raw)),
        "exact_duplicates_found": int(duplicates_before),
        "exact_duplicates_removed": int(removed),
        "rows_after": int(len(clean)),
        "row_id_column": ROW_ID,
        "row_id_note": "Positional counter for traceability. Not a person/host/session identifier.",
        "privacy_review": review,
        "class_counts_after_cleaning": {
            str(k): int(v) for k, v in clean[cfg["dataset"]["label_column"]].value_counts().items()
        },
    }
    write_json(cfg.path("metrics_dir") / "cleaning_report.json", cleaning_record)

    for protocol in PROTOCOLS:
        splits = build_splits(
            clean,
            cfg["splits"],
            seed=cfg.seed,
            protocol=protocol,
            label_column=cfg["dataset"]["label_column"],
            normal_label=cfg["dataset"]["normal_label"],
        )
        meta = split_metadata(
            clean,
            splits,
            cfg["splits"],
            seed=cfg.seed,
            protocol=protocol,
            label_column=cfg["dataset"]["label_column"],
            normal_label=cfg["dataset"]["normal_label"],
            dataset_fingerprint=fingerprint,
        )
        out_dir = cfg.path("splits_dir") / protocol
        write_splits(out_dir, splits, meta)
        print(
            f"[{protocol}] train={meta['splits']['train']['n_rows']:,} "
            f"validation={meta['splits']['validation']['n_rows']:,} "
            f"test={meta['splits']['test']['n_rows']:,} "
            f"| PortScan excluded from tuning: {meta['portscan_exclusion_confirmed']}"
        )
        print(f"          frozen to {out_dir}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
